name: build

on:
  push:
  pull_request:

jobs:
  cpu:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset cpu-release
      - name: Build
        run: cmake --build --preset cpu-release
      - name: Test
        run: ctest --preset cpu-release
